#!/bin/bash

# export LD_LIBRARY_PATH=/usr/local/lib
# export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

# gcc -o test_pocketsphinx test_pocketsphinx_with_gem5_main.cc -DMODELDIR=\"`pkg-config --variable=modeldir pocketsphinx`\" -L/user/local/lib `pkg-config --cflags --libs pocketsphinx sphinxbase`

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# "/mnt/__home__/git/nd/classes/grad_arch/ArchProjectObjC/gem5_src"
FRATES=("40" "50" "60" "70" "80")
NAME="iPadMini3"
MEM_SIZE="1GB"
L1D_SIZE="64kB"
L1I_SIZE="64kB"
L2_SIZE="1MB"
L3_SIZE="4MB"

L1D_ASSOC=4
L1I_ASSOC=4
L2_ASSOC=8
L3_ASSOC=2
CACHELINE_SIZE=64

NUM_CPUS=2

gcc -static -o run_pocketsphinx main.cc -DMODELDIR=\"${THIS_DIR}/pocketsphinx/model\" -I${THIS_DIR}/include -I${THIS_DIR}/include/sphinxbase -I${THIS_DIR}/include/pocketsphinx -L${THIS_DIR}/lib -lpocketsphinx -lsphinxbase -lsphinxad -lpthread -lm

# iPadMini3 -> A7
# iPadMini4 -> A8
# iPhone6s  -> A9
# iPhone7   -> A10 Fusion
# IPhone8+  -> A11 Bionic

# L1 -> 4 way associative
# L2 -> 8 way associative
# Apple A7 chip caches: L1 -> 64KB, L2=1MB, L3=4MB, RAM=1GB, 2 cores
# Apple A8 chip caches: L1 -> 64KB, L2=1MB, L3=4MB, RAM=1GB, 2 cores
# Apple A9 chip caches: L1 -> 64KB, L2=3MB, L3=4MB, RAM=2GB, 4 cores
# Apple A10 Fusion chip caches: L1 -> 64KB, L2=3MB, L3=4MB, RAM=2GB 4 cores
# Apple A11 Bionic chip chaces: L1 -> 32KB, L2=8MB, L3=None, RAM=3GB, 6 cores

for FR in ${FRATES[@]}; do
    ./../../gem5/build/X86/gem5.opt --stats-file=${THIS_DIR}/gem5_out/stats_${NAME}_${FR}.txt ./../../gem5/configs/example/se.py --cpu-type="DerivO3CPU" --num-cpus=${NUM_CPUS} --cacheline_size=${CACHELINE_SIZE} --mem-size=${MEM_SIZE} --l1d_size=${L1D_SIZE} --l1i_size=${L1I_SIZE} --l1i_assoc=${L1I_ASSOC} --l1d_assoc=${L1D_ASSOC} --l2_size=${L2_SIZE} --l2_assoc=${L2_ASSOC} --l3_size=${L3_SIZE} --l3_assoc=${L3_ASSOC} --caches --l2cache -c ./run_pocketsphinx --options=${FR}
done

